spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
    password:

  jpa:
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: truel
