springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/leteatgo-api.yaml
    path: /docs/swagger

external:
  kakao:
    key: ${KAKAO_KEY}

coolsms:
  key: ${COOLSMS_API_KEY}
  secret: ${COOLSMS_API_SECRET}
  from: ${COOLSMS_FROM}

jwt:
  secret: ${JWT_SECRET}
  issuer: leteatgo

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS}
        secret-key: ${AWS_SECRET}
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      file-size-threshold: 2MB
      location: /tmp/s3
      max-file-size: 2MB
      max-request-size: 2MB

aws:
  s3:
    bucket: ${S3_BUCKET}

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 10
        slow-call-rate-threshold: 10
        slow-call-duration-threshold: 500
        wait-duration-in-open-state: 30000
        permitted-number-of-calls-in-half-open-state: 5
        minimum-number-of-calls: 10
        register-health-indicator: true
    instances:
      searchRestaurants:
        base-config: default
        failure-rate-threshold: 50
        minimum-number-of-calls: 100

management:
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
