server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    open-in-view: false
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/leteatgo-api.yaml
    path: /docs/swagger

coolsms:
  key: ${COOLSMS_API_KEY}
  secret: ${COOLSMS_API_SECRET}
  from: ${COOLSMS_FROM}

jwt:
  secret: ${JWT_SECRET}
  issuer: leteatgo
