FROM nginx:latest

ARG ENV
COPY .docker/nginx/nginx-${ENV}.conf /etc/nginx/conf.d/default.conf
COPY .docker/nginx/nginx-green.conf /etc/nginx/nginx-green.conf
COPY .docker/nginx/nginx-blue.conf /etc/nginx/nginx-blue.conf