### search restaurants
GET {{host}}/api/tasty-restaurants/search?keyword=감자탕

### search restaurants with distance
GET {{host}}/api/tasty-restaurants/search?keyword=감자탕&longitude=127.06283102249932&latitude=37.514322572335935&sort=distance

### get popular keywords
GET {{host}}/api/tasty-restaurants/popular