openapi: 3.0.1
info:
  title: Let-Eat-Go API
  description: Spring REST Docs with SwaggerUI
  version: 0.0.1
servers:
- url: http://localhost:8080
- url: https://backend-dev.leteatgo.site
tags: []
paths:
  /api/tasty-restaurants:
    get:
      tags:
      - TastyRestaurants
      summary: 회원들이  방문한 맛집 조회
      description: 회원들이  방문한 맛집 조회
      operationId: 회원들이 방문한 맛집 조회
      parameters:
      - name: page
        in: query
        description: 요청 페이지
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/VisitedRestaurantResponse'
              examples:
                회원들이 방문한 맛집 조회:
                  value: "{\"contents\":[{\"name\":\"삼환소한마리\",\"category\":\"KOREAN_CUISINE\"\
                    ,\"phoneNumber\":\"02-545-2429\",\"roadAddress\":\"도로명\",\"landAddress\"\
                    :\"지번\",\"latitude\":127.06283102249932,\"longitude\":37.514322572335935,\"\
                    restaurantUrl\":\"http://place.map.kakao.com/8137464\",\"numberOfUses\"\
                    :100}]}"
  /api/auth/check-email:
    post:
      tags:
      - auth
      summary: 이메일 중복 검사
      description: 이메일 중복 검사
      operationId: 이
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
            examples:
              이미 존재하는 이메일:
                value: "{\"email\":\"test@naver.com\"}"
              이메일 중복 검사:
                value: "{\"email\":\"test@naver.com\"}"
      responses:
        "400":
          description: "400"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
              examples:
                이미 존재하는 이메일:
                  value: "{\"code\":\"ALREADY_EXIST_EMAIL\",\"message\":\"이미 존재하는\
                    \ 이메일입니다.\"}"
        "200":
          description: "200"
  /api/auth/send-sms:
    post:
      tags:
      - auth
      summary: 핸드폰 인증번호 발송
      description: 핸드폰 인증번호 발송
      operationId: 핸드폰 인증번호 발송
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
            examples:
              핸드폰 인증번호 발송:
                value: "{\"phoneNumber\":\"01012345678\"}"
      responses:
        "200":
          description: "200"
  /api/auth/signin:
    post:
      tags:
      - auth
      summary: 로컬 로그인
      description: 로컬 로그인
      operationId: 로컬 로그인
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
            examples:
              로컬 로그인:
                value: "{\"email\":\"test@naver.com\",\"password\":\"1!qweqwe\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
              examples:
                로컬 로그인:
                  value: "{\"accessToken\":\"eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTcwNjA3NDI5MywiZXhwIjoxNzA4NjY2MjkzLCJpc3MiOiJsZXRlYXRnbyJ9.pRsIGFVZQ8p_WX-Zw2Rf5eQNwfK1xHKA-UFDczzQzt4\"\
                    }"
  /api/auth/signout:
    delete:
      tags:
      - auth
      summary: 로그아웃
      description: 로그아웃
      operationId: 로그아웃
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
            examples:
              로그아웃:
                value: _csrf=4kFxZ0sTyVuEv2SM4spjjqnGjasV2qrvAHDNh1Yx2Hm_W33VhnVAUHIh-2Op2VPv0edX7Zz0oJIjvJ_CMEj6tWIB6EuHbhy3
      responses:
        "200":
          description: "200"
  /api/auth/signup:
    post:
      tags:
      - auth
      summary: 로컬 회원가입
      description: 로컬 회원가입
      operationId: 로컬 회원가입비밀번호 불일치아직 인증되지 않은 핸드폰 번호이미 가입된 핸드폰 번호
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
            examples:
              비밀번호 불일치:
                value: "{\"email\":\"test@naver.com\",\"nickname\":\"testnick\",\"\
                  password\":\"1!qweqwe\",\"passwordCheck\":\"1!qweqwe\",\"phoneNumber\"\
                  :\"01012345678\",\"authCode\":\"123456\"}"
              로컬 회원가입:
                value: "{\"email\":\"test@naver.com\",\"nickname\":\"testnick\",\"\
                  password\":\"1!qweqwe\",\"passwordCheck\":\"1!qweqwe\",\"phoneNumber\"\
                  :\"01012345678\",\"authCode\":\"123456\"}"
              아직 인증되지 않은 핸드폰 번호:
                value: "{\"email\":\"test@naver.com\",\"nickname\":\"testnick\",\"\
                  password\":\"1!qweqwe\",\"passwordCheck\":\"1!qweqwe\",\"phoneNumber\"\
                  :\"01012345678\",\"authCode\":\"123456\"}"
              이미 가입된 핸드폰 번호:
                value: "{\"email\":\"test@naver.com\",\"nickname\":\"testnick\",\"\
                  password\":\"1!qweqwe\",\"passwordCheck\":\"1!qweqwe\",\"phoneNumber\"\
                  :\"01012345678\",\"authCode\":\"123456\"}"
      responses:
        "400":
          description: "400"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
              examples:
                비밀번호 불일치:
                  value: "{\"code\":\"WRONG_PASSWORD\",\"message\":\"비밀번호가 일치하지 않습\
                    니다.\"}"
                이미 가입된 핸드폰 번호:
                  value: "{\"code\":\"ALREADY_EXIST_PHONE_NUMBER\",\"message\":\"이\
                    미 존재하는 핸드폰 번호입니다.\"}"
        "201":
          description: "201"
          headers:
            Location:
              description: 회원가입된 회원의 URI
              schema:
                type: string
        "401":
          description: "401"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
              examples:
                아직 인증되지 않은 핸드폰 번호:
                  value: "{\"code\":\"PHONE_NUMBER_NOT_VERIFIED\",\"message\":\"핸드\
                    폰 번호 인증이 완료되지 않았습니다.\"}"
  /api/tasty-restaurants/popular:
    get:
      tags:
      - TastyRestaurants
      summary: 인기 검색어 목록 조회
      description: 인기 검색어 목록 조회
      operationId: 인기 검색어
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-tasty-restaurants-popular-211251346'
              examples:
                인기 검색어:
                  value: "{\"contents\":[{\"keyword\":\"돼지국밥\",\"score\":10},{\"keyword\"\
                    :\"안심\",\"score\":5}]}"
  /api/tasty-restaurants/search:
    get:
      tags:
      - TastyRestaurants
      summary: 맛집 검색
      description: 맛집을 검색한다.
      operationId: 맛집 검색
      parameters:
      - name: keyword
        in: query
        description: 키워드
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: 페이지
        required: false
        schema:
          type: string
      - name: longitude
        in: query
        description: 경도(x)
        required: false
        schema:
          type: string
      - name: latitude
        in: query
        description: 위도(y)
        required: false
        schema:
          type: string
      - name: radius
        in: query
        description: 반경
        required: false
        schema:
          type: string
      - name: sort
        in: query
        description: 정렬
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/SearchRestaurantResponse'
              examples:
                맛집 검색:
                  value: |-
                    {
                      "contents" : [ {
                        "apiId" : 123456,
                        "name" : "삼환소한마리",
                        "category" : "KOREAN_CUISINE",
                        "phoneNumber" : "02-545-2429",
                        "roadAddress" : "도로명",
                        "landAddress" : "지번",
                        "latitude" : 37.514322572335935,
                        "longitude" : 127.06283102249932,
                        "restaurantUrl" : "http://place.map.kakao.com/8137464"
                      } ],
                      "pagination" : {
                        "currentPage" : 1,
                        "hasMore" : true,
                        "totalCount" : 1234
                      }
                    }
  /api/chat/rooms/me:
    get:
      tags:
      - ChatRoom
      summary: 내 채팅방 목록 조회
      description: 내 채팅방 목록 조회
      operationId: 내 채팅방 목록 조회
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
              examples:
                내 채팅방 목록 조회:
                  value: "{\"contents\":[{\"meetingName\":\"meeting name\",\"category\"\
                    :\"ASIAN_CUISINE\",\"regin\":\"지역\",\"roomId\":1,\"content\":\"\
                    recent message\",\"createdAt\":null,\"read\":false}],\"pagination\"\
                    :{\"currentPage\":0,\"hasMore\":true}}"
  /api/chat/rooms/{roomId}/messages:
    get:
      tags:
      - ChatRoom
      summary: 채팅방 대화 목록 조회
      description: 채팅방 대화 목록 조회
      operationId: 채팅방 대화 목록 조회
      parameters:
      - name: roomId
        in: path
        description: 채팅방 id
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/api-chat-rooms-roomId-messages486549215'
              examples:
                채팅방 대화 목록 조회:
                  value: "{\"contents\":[{\"sender\":{\"senderId\":1,\"nickname\"\
                    :\"nick\",\"profile\":\"profile\"},\"content\":\"message 1\",\"\
                    isRead\":true,\"createdAt\":\"2024-02-01 20:19\"}],\"pagination\"\
                    :{\"currentPage\":0,\"hasMore\":true}}"
components:
  schemas:
    api-tasty-restaurants-popular-211251346:
      type: object
      properties:
        contents:
          type: array
          items:
            required:
            - keyword
            - score
            type: object
            properties:
              score:
                type: number
                description: 검색한 횟수
              keyword:
                type: string
                description: 키워드
    VisitedRestaurantResponse:
      title: VisitedRestaurantResponse
      type: object
      properties:
        contents:
          type: array
          items:
            required:
            - category
            - landAddress
            - latitude
            - longitude
            - name
            - numberOfUses
            - phoneNumber
            - restaurantUrl
            - roadAddress
            type: object
            properties:
              phoneNumber:
                type: string
                description: 전화번호
              landAddress:
                type: string
                description: 지번 주소
              latitude:
                type: number
                description: 경도
              roadAddress:
                type: string
                description: 도로명 주소
              numberOfUses:
                type: number
                description: 방문 횟수
              restaurantUrl:
                type: string
                description: 식당 url
              name:
                type: string
                description: 식당 이름
              category:
                type: string
                description: 카테고리
              longitude:
                type: number
                description: 위도
    SearchRestaurantResponse:
      title: SearchRestaurantResponse
      type: object
      properties:
        pagination:
          required:
          - currentPage
          - hasMore
          - totalCount
          type: object
          properties:
            hasMore:
              type: boolean
              description: 다음 페이지 여부
            totalCount:
              type: number
              description: 전체 컨텐츠 개수
            currentPage:
              type: number
              description: 현재 페이지
        contents:
          type: array
          items:
            required:
            - apiId
            - category
            - landAddress
            - latitude
            - longitude
            - name
            - phoneNumber
            - restaurantUrl
            - roadAddress
            type: object
            properties:
              phoneNumber:
                type: string
                description: 전화번호
              landAddress:
                type: string
                description: 지번 주소
              latitude:
                type: number
                description: 경도
              roadAddress:
                type: string
                description: 도로명 주소
              restaurantUrl:
                type: string
                description: 식당 url
              name:
                type: string
                description: 식당 이름
              category:
                type: string
                description: 카테고리
              apiId:
                type: number
                description: 식당 아이디
              longitude:
                type: number
                description: 위도
    api-chat-rooms-roomId-messages486549215:
      type: object
