version: '3.7'
name: leteatgo

services:
  leteatgo-redis:
    image: redis:alpine
    container_name: leteatgo-redis
    environment:
      - appendonly=yes
      - appendfsync=everysec
      - auto-aof-rewrite-percentage=100
      - auto-aof-rewrite-min-size=64mb
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - leteatgo
    restart: always

networks:
  leteatgo:
    driver: bridge