version: '3.7'

services:
  leteatgo-server:
    image: kingseungil/leteatgo-backend-dev:latest
    container_name: leteatgo-server
    expose:
      - "8080"
    restart: always
    depends_on:
      - leteatgo-redis
      - leteatgo-rabbitmq
    networks:
      - leteatgo

  leteatgo-nginx:
    image: kingseungil/leteatgo-nginx-dev:latest
    container_name: leteatgo-nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - leteatgo

  leteatgo-redis:
    image: redis:alpine
    container_name: leteatgo-redis
    environment:
      - appendonly=yes
      - appendfsync=everysec
      - auto-aof-rewrite-percentage=100
      - auto-aof-rewrite-min-size=64mb
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - leteatgo
    restart: always

  leteatgo-rabbitmq:
    image: kingseungil/leteatgo-rabbitmq-dev:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - leteatgo

networks:
  leteatgo:
    external: true