version: '3.7'
name: leteatgo

services:
  leteatgo-server:
    image: kingseungil/leteatgo-backend-dev:latest
    container_name: leteatgo-server
    expose:
      - "8080"
    restart: always
    networks:
      - leteatgo
  
  leteatgo-nginx:
    image: kingseungil/leteatgo-nginx-dev:latest
    container_name: leteatgo-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx-dev.conf
    networks:
      - leteatgo

  leteatgo-redis:
    image: redis:alpine
    container_name: leteatgo-redis
    environment:
      - appendonly=yes
      - appendfsync=everysec
      - auto-aof-rewrite-percentage=100
      - auto-aof-rewrite-min-size=64mb
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - leteatgo
    restart: always

networks:
  leteatgo:
    driver: bridge