FROM khipu/openjdk17-alpine:latest

ARG ENV
ENV SPRING_PROFILES_ACTIVE=${ENV}
COPY build/libs/*.jar app.jar
COPY build/resources/main/properties/env.properties properties/env.properties
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}", "app.jar"]