name: CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set env.properties
        run: |
          cd ./src/main/resources
          mkdir -p properties
          cd properties
          touch ./env.properties
          echo "${{ secrets.ENV_PROPERTIES }}" > ./env.properties

      - name: Set docker .env
        run: |
          cd .docker
          touch .env
          echo "${{ secrets.DOCKER_ENV }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: generate SwaggerUI
        uses: gradle/gradle-build-action@v2
        with:
          arguments: generateSwaggerUI

      - name: Push Springboot Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/api/Dockerfile-api
          push: true
          tags: |
            kingseungil/leteatgo-backend-dev:latest
            kingseungil/leteatgo-backend-dev:${{ github.sha }}
          build-args: |
            ENV=dev

      - name: Push Nginx Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/nginx/Dockerfile-nginx
          push: true
          tags: |
            kingseungil/leteatgo-nginx-dev:latest
            kingseungil/leteatgo-nginx-dev:${{ github.sha }}
          build-args: |
            ENV=dev

      - name: Push RabbitMQ Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/rabbitmq/Dockerfile-rabbitmq
          push: true
          tags: |
            kingseungil/leteatgo-rabbitmq-dev:latest
            kingseungil/leteatgo-rabbitmq-dev:${{ github.sha }}

      - name: Deploy to GCP
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.GCP_TEST_USERNAME }}
          host: ${{ secrets.GCP_TEST_HOST }}
          key: ${{ secrets.GCP_TEST_SSH_KEY }}
          script: |
            cd ~/backend
            git checkout dev
            git pull origin dev
            cd ~/backend/.docker
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker-compose -f docker-compose-dev.yml up -d --build
            docker image prune -f --filter "until=24h"